/*
 * This file is generated by jOOQ.
*/
package org.learning.jooq.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.learning.jooq.model.tables.UserDetails;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetailsRecord extends UpdatableRecordImpl<UserDetailsRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = -751265923;

    /**
     * Setter for <code>public.user_details.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_details.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_details.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_details.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_details.mobile</code>.
     */
    public void setMobile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_details.mobile</code>.
     */
    public String getMobile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_details.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_details.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    
    public Field<Long> field1() {
        return UserDetails.USER_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    
    public Field<String> field2() {
        return UserDetails.USER_DETAILS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    
    public Field<String> field3() {
        return UserDetails.USER_DETAILS.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    
    public Field<String> field4() {
        return UserDetails.USER_DETAILS.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    
    public String value3() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    
    public String value4() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    
    public UserDetailsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    
    public UserDetailsRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    
    public UserDetailsRecord value3(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    
    public UserDetailsRecord value4(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    
    public UserDetailsRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDetailsRecord
     */
    public UserDetailsRecord() {
        super(UserDetails.USER_DETAILS);
    }

    /**
     * Create a detached, initialised UserDetailsRecord
     */
    public UserDetailsRecord(Long id, String email, String mobile, String username) {
        super(UserDetails.USER_DETAILS);

        set(0, id);
        set(1, email);
        set(2, mobile);
        set(3, username);
    }
}
