/*
 * This file is generated by jOOQ.
*/
package org.learning.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetails implements Serializable {

    private static final long serialVersionUID = -780217062;

    private Long   id;
    private String email;
    private String mobile;
    private String username;

    public UserDetails() {}

    public UserDetails(UserDetails value) {
        this.id = value.id;
        this.email = value.email;
        this.mobile = value.mobile;
        this.username = value.username;
    }

    public UserDetails(
        Long   id,
        String email,
        String mobile,
        String username
    ) {
        this.id = id;
        this.email = email;
        this.mobile = mobile;
        this.username = username;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDetails (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
