/*
 * This file is generated by jOOQ.
*/
package org.learning.jooq.model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.hibernate_sequence</code>
     */
    public static final Sequence<Long> HIBERNATE_SEQUENCE = new SequenceImpl<Long>("hibernate_sequence", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
