/*
 * This file is generated by jOOQ.
*/
package org.learning.jooq.model;


import javax.annotation.Generated;

import org.learning.jooq.model.tables.UserDetails;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user_details</code>.
     */
    public static final UserDetails USER_DETAILS = org.learning.jooq.model.tables.UserDetails.USER_DETAILS;
}
